sftp:
  Env: "loc"
  Host: "sftp.px.bylinkr.com"
  Port: "8422"
  User: "linkr"
  Password: "linkr2026"
  working-directory: "upload/theu"
  working-directory-product: "upload/theu/Herve/Local"
  filename: "invoices.json"
  filename-product: "products.csv"